name: Upload binaries to release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: u64viewer-linux_amd64
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            asset_name: u64viewer-darwin_amd64
            target: x86_64-apple-darwin
          - os: macos-latest
            asset_name: u64viewer-darwin_arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            asset_name: u64viewer-windows_amd64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            asset_name: u64viewer-windows_arm64
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Set Cargo.toml version (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          mv Cargo.toml Cargo.toml.orig
          sed "s|version = \".*-git\"|version = \"${VERSION}\"|" Cargo.toml.orig > Cargo.toml
          cargo update -p u64viewer --offline || cargo generate-lockfile

      - name: Set Cargo.toml version (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF_NAME -replace '^v', ''
          (Get-Content ./Cargo.toml) -replace 'version = ".*-git"', "version = ""$version""" | Set-Content Cargo.toml
          cargo update -p u64viewer --offline
          if ($LASTEXITCODE -ne 0) { cargo generate-lockfile }

      - if: matrix.os == 'ubuntu-latest'
        name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install libasound2-dev musl-tools -y

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/${{ matrix.target }}/release/u64viewer${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          asset_name: ${{ matrix.asset_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
